# PyTorch

### 5 Interesting functions related to PyTorch

An short introduction about PyTorch and about the chosen functions. 
- torch.tensor()
- torch.zeros()
- torch.arange()
- torch.linespace()
- torch.eye()

In [7]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.tensor ()

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor.

In [8]:
# Example 1 - initialising (through list)
torch.tensor([[1, 2], [3, 4.]])

tensor([[1., 2.],
        [3., 4.]])

1. All lists must be of same length
2. Notice the last element while initialising(4.) the "." here specifies the float nature of the number, in a tensor if atleast one number is initialised with float notation, the whole tensor will modify to float.

In [9]:
# Example 2 - initialising (through numpy array, all array must be of same length)
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

1. Here also all array must be of same length.
2. Notice now all elements of each and every array are without float notation(integers), so the output is an integer tensor.

In [10]:
# Example 3 - breaking (to illustrate when it breaks, as second list is of size 3)
torch.tensor([[1, 2], [3, 4, 5]])

ValueError: expected sequence of length 2 at dim 1 (got 3)

According to Value error: Since 1st list of size 2 the 2nd must also be the same, 2nd expected 2 elements but got 3.

## Function 2 - torch.zeros()

Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

In [11]:
# Example 1
torch.zeros(11,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

Create a matrix of 11 rows and 2 columns , filled with zeros

In [12]:
# Example 2
torch.zeros(10 , requires_grad=True)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

Ten rows of zeros with requires_grad set to True

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
torch.zeros(03)

SyntaxError: invalid token (<ipython-input-14-c36daa30f3c7>, line 2)

We should not use 02 when passing the int to the zeros, 02 is not as same as 2.

-> We should use this function when we need a matrix with zeros.

## Function 3 - torch.arange()
Returns a 1-D tensor of size end-start/step with values from the interval [start, end] taken with common difference step beginning from start.


In [15]:
# Example 1
torch.arange(start=0,end=10,step=3)

tensor([0, 3, 6, 9])

We create a tensor using arange function where we give start to be 0 and end to be 10 wit step 3 . So the first value will be zero and later i+3,



In [18]:
# Example 2
torch.arange(1,1.5,0.2)

tensor([1.0000, 1.2000, 1.4000])

We can also give it a float value and in return we get a list of tensors .

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange([1,2,3])

TypeError: arange(): argument 'end' (position 1) must be Number, not list

We cannot pass list when creating a tensor using arange , it only accepts start , end and step



*Use this function when you need a specific tensors values

## Function 4 - torch.linspace()
Returns a one-dimensional tensor of steps equally spaced points between start and end.

The output tensor is 1-D of size steps.


In [21]:
# Example 1
torch.linspace(10,5)

tensor([10.0000,  9.9495,  9.8990,  9.8485,  9.7980,  9.7475,  9.6970,  9.6465,
         9.5960,  9.5455,  9.4949,  9.4444,  9.3939,  9.3434,  9.2929,  9.2424,
         9.1919,  9.1414,  9.0909,  9.0404,  8.9899,  8.9394,  8.8889,  8.8384,
         8.7879,  8.7374,  8.6869,  8.6364,  8.5859,  8.5354,  8.4848,  8.4343,
         8.3838,  8.3333,  8.2828,  8.2323,  8.1818,  8.1313,  8.0808,  8.0303,
         7.9798,  7.9293,  7.8788,  7.8283,  7.7778,  7.7273,  7.6768,  7.6263,
         7.5758,  7.5253,  7.4747,  7.4242,  7.3737,  7.3232,  7.2727,  7.2222,
         7.1717,  7.1212,  7.0707,  7.0202,  6.9697,  6.9192,  6.8687,  6.8182,
         6.7677,  6.7172,  6.6667,  6.6162,  6.5657,  6.5152,  6.4646,  6.4141,
         6.3636,  6.3131,  6.2626,  6.2121,  6.1616,  6.1111,  6.0606,  6.0101,
         5.9596,  5.9091,  5.8586,  5.8081,  5.7576,  5.7071,  5.6566,  5.6061,
         5.5556,  5.5051,  5.4545,  5.4040,  5.3535,  5.3030,  5.2525,  5.2020,
         5.1515,  5.1010,  5.0505,  5.00

Create a random data start with 10 and end in 5

In [22]:
# Example 2
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

From 1 to 10 get a 5 equally distributed data sets.

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(10)

TypeError: linspace() missing 1 required positional arguments: "end"

We should pass ending argument to the linspace because the function needs to know when it should end

*We should use this function to get random data points with start and end as default points

## Function 5 - torch.eye()

Return identity matrix ( Identity matrix is something which we need when we are finding the inverse of the matrix)

In [24]:
# Example 1
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

Return a 2 by 2 identity matrix

In [25]:
# Example 2
torch.eye(n=3,m=4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

Create a 2d identity matrix with 3 rows and 4 columms

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye(n=3,m=5 , dtype='float')

TypeError: eye() received an invalid combination of arguments - got (dtype=str, n=int, m=int, ), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


We should provide torch.float to get a float values rather using float as string

*Use this function when we need to create an identity matrix to find an inverse of an matrix

### Conclusion

These 5 basic functions are pretty useful. We saw how create a zero matrix, initialize a random matrix, create an identity matrix to help find inverse of matrices and also how to create tensors.There are hundreds of useful tensor functions which we can use , for more information please go to offical python documentation.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [27]:
!pip install jovian --upgrade --quiet

In [28]:
import jovian

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "kumarsahuyash007/01-tensor-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumarsahuyash007/01-tensor-operations


'https://jovian.ml/kumarsahuyash007/01-tensor-operations'